myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"
urlpatterns = [
    path('', views.index, name='index'),
    path('plus/', views.plus, name='plus'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

myapp/models.py
from django.db import models


class Person(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    is_wedding = models.BooleanField(default= False)

myapp/views.py
from django.shortcuts import render, redirect
from myapp.models import Person

def index(request):
    searchname = request.GET.get("my_param", "")
    if searchname == "":
        w = Person.objects.filter(is_wedding = 0).order_by("-price")
        m = Person.objects.filter(is_wedding = 1).order_by("-price")
    else:
        w = Person.objects.filter(is_wedding = 0).filter(name__contains = searchname).order_by("-price")
        m = Person.objects.filter(is_wedding = 0).filter(name__contains = searchname).order_by("-price")
    
    sum_price = 0
    women = [("없음", 0)]
    w_total = 0
    men = [("없음", 0)]
    m_total = 0
    for i in w:
        women.append((i.name, i.price))
        w_total += i.price

    for i in m:
        men.append((i.name, i.price))
        m_total += i.price
    women.sort(key=lambda x: x[0])
    men.sort(key=lambda x:x[0])
    print(women[0], men[0])
    context = {'my_data_w' : w, 'my_data_m' : m,'sum_data' : w_total + m_total, 'women_MVP' : women[0][0], 'women_price' : women[0][1], 'men_MVP' : men[0][0], 'men_price': men[0][1], 'w_count' : len(women), 'm_count' : len(men)}
    return render(request, 'index.html', context)

def plus(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        is_wedding = request.POST.get('women')
        print(111111)
        if is_wedding == "option1": 
            is_wedding = 1
        else:
            is_wedding = 0
        person = Person(name=name, price=price, is_wedding=is_wedding)
        person.save()
        return redirect("myapp:index")

myapp/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>MyApp - Index</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body class="mx-5 my-5 text-center">
    <h1 class='text-center'>축의금 리스트</h1>
    <div class="row">
        <form method="POST" action="{% url 'myapp:plus' %}" class='row'>
            {% csrf_token %}
            <div class="col-2">
                <input type="text" id="name" name="name" class="form-control" placeholder="이름 입력">
            </div>
            <div class="col-2">
                <input type="number" id="price" name="price" class="form-control" placeholder="축의금 입력">
            </div>
            <div class="col-2">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="women" id="option1" value = "option1">
                    <label class="form-check-label" for="women">
                      신랑측
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="women" id="option2" value =  checked>
                    <label class="form-check-label" for="women">
                      신부측
                    </label>
                  </div>
            </div>
            <div class="col-2">
                <button type="submit" class="btn btn-outline-success">추가하기</button>
            </div>
        </form>
    </div>

    <form action="{% url 'myapp:index' %}" method="get">
        <input type="text" name="my_param" placeholder="이름을 입력하세요!">
        <button type="submit" class="btn btn-outline-primary">되돌리기</button>
        <button type="submit" class="btn btn-outline-primary">검색하기</button>
    </form>
    <div class="row">
        <div class = "col-5">
            <h1>신부 고객님</h1>
            <ol class="list-group list-group-numbered">
                {% for data in my_data_w %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">{{data.name}}
                    {% if data.is_wedding == True %}
                        (신랑측)
                    {% else %}
                        (신부측)
                    {% endif %}
                    </div>
                    축의금 : {{data.price}}
                </div>
                </li>
                {% endfor %}
            </ol>
            신부측 MVP : {{women_MVP}} / 신부측 금액 : {{women_price}} / 신부 방문객 : {{w_count}}
        </div>
        <div class="col-5">
            <h1>신랑 고객님</h1>
            <ol class="list-group list-group-numbered">
                {% for data in my_data_m %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">{{data.name}}
                    {% if data.is_wedding == True %}
                        (신랑측)
                    {% else %}
                        (신부측)
                    {% endif %}
                    </div>
                    축의금 : {{data.price}}
                </div>
                </li>
                {% endfor %}
            </ol>
            신랑측 MVP : {{men_MVP}} / 신랑측 금액 :  {{men_price}} / 신랑 방문객 :{{m_count}}
        </div>
    </div>
    <div class='row mt-5'>
        <div class='col-4'>
        <h1> 합계 : {{sum_data}} <h1>
        </div>
        <div class='col-4'>
        <h1> 총괄 MVP : </h1>
        </div>
    </div>
    <h1 class='text-center'>개발자 후원 : 신한 110-431-910472</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>